# 서버설정
server:

  # 서비스포트
  port: 8080

  # 톰캣설정
  tomcat:

    basedir: .

    accesslog:
      enabled: true
      pattern: '%{host}i %h %l %u %t "%r" %s %b %D "%{User-Agent}i"'
      directory: accesslogs
      suffix: .log
      prefix: access_log
      max-days: 10
      file-date-format: _yyyy-MM-dd



# AP log설정
logging:

  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] - %cyan(%logger{35}) : %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] - %logger{35} : %msg%n'
    rolling-file-name: "logs/ap.log.%d{yyyy-MM-dd}.%i"

  file:
    name: logs/ap.log
    max-history: 10

  level:
    root: INFO



# AP에서 사용하는 프로퍼티
elasticsearch:

  host: 152.70.235.78
  protocol: https
  port: 9200

  user:
    id: elastic
    pw: 1qazxsw2!
